blogTitle = "Your Title Here"
subTitle = "your subtitle here"
blogUrl = "http://whatever.com"
authorName = "Danni Konsumer"
authorBio = "<span>Written by:</span>Danni Konsumer"
linkPrefix = "/gatsby-starter-drunkenblog"
# gaCode = "UA-0000000-0"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"
